server:
  port: 8080

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: book-service
          uri: http://localhost:8085
          predicates:
            - Path=/books/**
        - id: user-service
          uri: http://localhost:8084
          predicates:
            - Path=/users/**
        - id: borrowing-service
          uri: http://localhost:8083
          predicates:
            - Path=/borrowings/**
  kafka:
    bootstrap-servers: localhost:9092
  config:
    import: optional:configserver:http://localhost:8888

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    hostname: localhost
    prefer-ip-address: true